# Generated by Django 2.2.5 on 2019-12-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity_template',
            unique_together=set(),
        ),
    ]
