# Generated by Django 2.2.5 on 2019-12-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191225_0742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity_template',
            unique_together={('name', 'entity_group_template', 'event_group_template')},
        ),
    ]
