# Generated by Django 2.2.5 on 2019-12-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191228_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review_allocation',
            unique_together=set(),
        ),
    ]
