# Generated by Django 2.2.5 on 2019-12-28 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20191228_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review_allocation',
            unique_together={('doc', 'reviewer')},
        ),
    ]
