# Generated by Django 2.2.5 on 2020-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200422_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='standard_name',
            field=models.CharField(max_length=20),
        ),
    ]
