# Generated by Django 2.2.5 on 2020-05-09 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200508_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='standard',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dic', to='api.Standard'),
        ),
        migrations.AlterField(
            model_name='dic',
            name='entity_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dic', to='api.Entity_template'),
        ),
    ]
