# Generated by Django 2.2.5 on 2020-05-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200509_0150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dic',
            unique_together={('project', 'content')},
        ),
    ]
