# Generated by Django 2.2.5 on 2020-05-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200509_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Re',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=100)),
                ('entity_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re', to='api.Entity_template')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re', to='api.Project')),
            ],
            options={
                'unique_together': {('project', 'content')},
            },
        ),
    ]
