# Generated by Django 2.2.5 on 2020-05-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re',
            name='entity_template',
        ),
        migrations.AddField(
            model_name='re',
            name='entity_template',
            field=models.ManyToManyField(related_name='re', to='api.Entity_template'),
        ),
    ]
