# Generated by Django 2.2.5 on 2020-05-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200510_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re',
            name='entity_template',
        ),
        migrations.CreateModel(
            name='Re_entity_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('entity_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_template', to='api.Entity_template')),
                ('re', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re', to='api.Re')),
            ],
            options={
                'unique_together': {('re', 'entity_template', 'order')},
            },
        ),
    ]
